/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const generateDonorEngagementRecommendation = require('./code/generateDonorEngagementRecommendation');
const generateDonorSummary = require('./code/generateDonorSummary');

class donorMgmtSrv extends LCAPApplicationService {
    async init() {

        this.on('__undefined__', 'Donors', async (request, next) => {
            return generateDonorEngagementRecommendation(request, next);
        });

        this.on('__undefined__', 'Donors', async (request, next) => {
            return generateDonorSummary(request, next);
        });

        return super.init();
    }
}


module.exports = {
    donorMgmtSrv
};