/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const donorSummary = require('./code/DonorSummary').default;
const generateDonorEngagementRecommendation = require('./code/generateDonorEngagementRecommendation');

class donorMgmtSrv extends LCAPApplicationService {
    async init() {

        this.on('DonorSummary', 'Donors', async (request) => {
            const donorsummary = await donorSummary(request);
            console.log(`Donor Summary:${donorsummary}`);
        });

        this.on('generateDonorEngagementRecommendation', 'Donors', async (request) => {
            await generateDonorEngagementRecommendation(request);
        });

        return super.init();
    }
}


module.exports = {
    donorMgmtSrv
};